# Generated by Django 3.0.8 on 2020-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_booking_prefered_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(max_length=10000),
        ),
    ]
